build: fix detecting of HAVE_V8_WITH_MOST_CONSTRUCTORS_ISOLATE
It can't link program because we need to link with libv8, however we can
avoid this by just checking whether specific function exist in header or
not, using sizeof().

With this patch next error is fixied:
src.cxx.o: In function `main':
src.cxx:(.text+0xa): undefined reference to `v8::Isolate::GetCurrent()'
src.cxx:(.text+0x21): undefined reference to `v8::HandleScope::HandleScope(v8::Isolate*)'
src.cxx:(.text+0x32): undefined reference to `v8::HandleScope::~HandleScope()'